In [4]:
from numpy import array
from scipy.linalg import svd
A=array([[9,2],[3,4],[5,6]])
print("A:\n%s" %A)
U,s,VT =svd(A)
print("\nU: \n%s" %U)
print("\ns: \n %s" %s)
print("\nV^T: \n%s" %VT)


A:
[[9 2]
 [3 4]
 [5 6]]

U: 
[[-0.70459717  0.70861441 -0.03752933]
 [-0.37760662 -0.41919339 -0.82564529]
 [-0.60079619 -0.56757601  0.56293997]]

s: 
 [12.34341639  4.31741494]

V^T: 
[[-0.84888778 -0.52857311]
 [ 0.52857311 -0.84888778]]
